//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public string UserID { get; set; }
        public string Password { get; set; }
        public string Fullname { get; set; }
        public string Phone { get; set; }
        public int Account_Role_ID { get; set; }
        public int Account_Status_ID { get; set; }
    
        public virtual Account_Roles Account_Roles { get; set; }
        public virtual Account_Status Account_Status { get; set; }
    }
}
