//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Car()
        {
            this.Invoice_Details = new HashSet<Invoice_Details>();
        }
    
        public int ID { get; set; }
        public string Model_Name { get; set; }
        public double Price { get; set; }
        public int Produced_Year { get; set; }
        public System.DateTime Accquired_Date { get; set; }
        public int Engine { get; set; }
        public int Quantity { get; set; }
        public int Manufacturer_ID { get; set; }
        public int Tranmission_ID { get; set; }
        public int Type_ID { get; set; }
        public int Category_ID { get; set; }
        public int Fuel_ID { get; set; }
        public int Status_ID { get; set; }
    
        public virtual Car_Categories Car_Categories { get; set; }
        public virtual Car_Fuels Car_Fuels { get; set; }
        public virtual Car_Manufacturers Car_Manufacturers { get; set; }
        public virtual Car_Status Car_Status { get; set; }
        public virtual Car_Tranmissions Car_Tranmissions { get; set; }
        public virtual Car_Types Car_Types { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice_Details> Invoice_Details { get; set; }
    }
}
